name: CI/CD AI Demo

on:
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      tests_failed: ${{ steps.set_test_result.outputs.tests_failed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests and save logs
        id: run_tests
        run: |
          PYTHONPATH=$(pwd) pytest tests/ --maxfail=1 --disable-warnings -q > failed_pipeline.log || echo "failed=true" >> $GITHUB_ENV

      - name: Set test result output
        id: set_test_result
        run: |
          if [[ "${{ env.failed }}" == "true" ]]; then
            echo "tests_failed=true" >> $GITHUB_OUTPUT
          else
            echo "tests_failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: failed-pipeline-log
          path: failed_pipeline.log

  ai-assistant:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai gh

      - name: Download logs
        uses: actions/download-artifact@v4
        with:
          name: failed-pipeline-log
          path: .

      - name: Run AI Assistant
        id: ai_assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [[ "${{ needs.build-and-test.outputs.tests_failed }}" == "true" ]]; then
              python scripts/ai_assistant.py > ai_output.log
          else
              echo "✅ All tests passed. PR can be merged!" > ai_output.log
          fi
          cat ai_output.log

      - name: Post PR comment with AI suggestion
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT=$(cat ai_output.log)
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
