name: CI/CD AI Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests and save logs
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q > failed_pipeline.log || true

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: failed-pipeline-log
          path: failed_pipeline.log

  ai-assistant:
    needs: build-and-test
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Download logs
        uses: actions/download-artifact@v4
        with:
          name: failed-pipeline-log
          path: .

      - name: Run AI Assistant
        if: hashFiles('failed_pipeline.log') != ''
        run: python scripts/ai_assistant.py
